template = "https://github.com/giellalt/template-lang-und"
rev_id = 291
template_sha = "4f5759693f3a379d63c31d91878cd6e3b56817ae"

[replacements]
__GLOTTOLOG_ID__ = "quen1234"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-qya"
__UND2C__ = "qya"
__UNDEFINED__ = "Quenya"
__UND__ = "qya"
