template = "https://github.com/giellalt/template-lang-und"
rev_id = 342
template_sha = "e424c1d2f80ec6b0f9d9f55694201f1677e0295b"

[replacements]
__GLOTTOLOG_ID__ = "quen1234"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-qya"
__UND2C__ = "qya"
__UNDEFINED__ = "Quenya"
__UND__ = "qya"
