# This template merge config file lists:
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
name = "Language Template"
patterns = ["qya", "qya", "Quenya", "GPLv3"]
rev_id = 42
required = ["configure.ac",
            ".gitignore",
            "tools/shellscripts/uqya-gt.sh.in",
            "tools/shellscripts/Makefile.am",
            "tools/mt/filters/Makefile.am",
            "tools/mt/Makefile.modifications.am",
            "tools/mt/Makefile.am",
            "tools/mt/apertium/filters/Makefile.am",
            "tools/mt/apertium/Makefile.modifications.am",
            "tools/mt/apertium/Makefile.am",
            "tools/mt/apertium/tagsets/Makefile.am",
            "tools/mt/cgbased/Makefile.am",
            "tools/hyphenators/filters/Makefile.am",
            "tools/hyphenators/Makefile.am",
            "tools/hyphenators/Makefile.modification-fst.am",
            "tools/hyphenators/Makefile.modification-pattern.am",
            "tools/spellcheckers/filters/Makefile.mod-mobile-filters.am",
            "tools/spellcheckers/filters/Makefile.am",
            "tools/spellcheckers/filters/Makefile.mod-desktop-filters.am",
            "tools/spellcheckers/filters/Makefile.mod-fstbased-filters.am",
            "tools/spellcheckers/Makefile.mod-spellcheckers.am",
            "tools/spellcheckers/weights/Makefile.am",
            "tools/spellcheckers/Makefile.mod-mobile-hfst.am",
            "tools/spellcheckers/Makefile.am",
            "tools/spellcheckers/Makefile.mod-fstbased.am",
            "tools/spellcheckers/Makefile.mod-desktop.am",
            "tools/spellcheckers/Makefile.mod-mobile.am",
            "tools/spellcheckers/Makefile.mod-desktop-hfst.am",
            "tools/Makefile.am",
            "tools/tokenisers/filters/Makefile.am",
            "tools/tokenisers/Makefile.am",
            "tools/analysers/Makefile.am",
            "tools/grammarcheckers/filters/Makefile.am",
            "tools/grammarcheckers/Makefile.am",
            "tools/grammarcheckers/tests/Makefile.am",
            "test/tools/mt/Makefile.am",
            "test/tools/mt/apertium/Makefile.am",
            "test/tools/mt/apertium/run-mt-gt-desc-anayaml-testcases.sh",
            "test/tools/hyphenators/fstbased/Makefile.am",
            "test/tools/hyphenators/Makefile.am",
            "test/tools/hyphenators/patternbased/Makefile.am",
            "test/tools/spellcheckers/fstbased/run-fstspeller-gt-norm-yaml-testcases.sh",
            "test/tools/spellcheckers/fstbased/desktop/hfst/run-acceptor-yaml-testcases.sh",
            "test/tools/spellcheckers/fstbased/desktop/hfst/Makefile.am",
            "test/tools/spellcheckers/fstbased/desktop/hfst/test-zhfst-basic-sugg-speed.sh.in",
            "test/tools/spellcheckers/fstbased/desktop/hfst/accept-all-lemmas.sh.in",
            "test/tools/spellcheckers/fstbased/desktop/Makefile.am",
            "test/tools/spellcheckers/fstbased/Makefile.am",
            "test/tools/spellcheckers/fstbased/mobile/Makefile.am",
            "test/tools/spellcheckers/test-zhfst-file.sh.in",
            "test/tools/spellcheckers/Makefile.am",
            "test/tools/spellcheckers/run-spellers-gt-norm-yaml-testcases.sh",
            "test/tools/Makefile.am",
            "test/run-yaml-testcases.sh.in",
            "test/check_lemmas.sh",
            "test/error-handling-stubs.sh",
            "test/run-morph-tester.sh.in",
            "test/Makefile.am",
            "test/src/run-gt-desc-genyaml-testcases.sh",
            "test/src/orthography/Makefile.am",
            "test/src/orthography/run-initcaps-genyaml-testcases.sh",
            "test/src/phonology/pair-test-negative.sh.in",
            "test/src/phonology/Makefile.am",
            "test/src/phonology/pair-test-hfst.sh.in",
            "test/src/phonology/pair-test-positive.sh.in",
            "test/src/run-dict-gt-desc-anayaml-testcases.sh",
            "test/src/run-gt-norm-genyaml-testcases.sh",
            "test/src/Makefile.am",
            "test/src/run-gt-norm-yaml-testcases.sh",
            "test/src/run-lexc-testcases.sh",
            "test/src/run-gt-norm-anayaml-testcases.sh",
            "test/src/run-gt-desc-yaml-testcases.sh",
            "test/src/morphology/generate-noun-lemmas.sh.in",
            "test/src/morphology/tag_test.sh",
            "test/src/morphology/generate-adjective-lemmas.sh.in",
            "test/src/morphology/Makefile.am",
            "test/src/morphology/generate-verb-lemmas.sh.in",
            "test/src/morphology/generate-propernoun-lemmas.sh.in",
            "test/src/run-gt-desc-anayaml-testcases.sh",
            "test/src/syntax/Makefile.am",
            "test/src/run-dict-gt-norm-genyaml-testcases.sh",
            "giella-qya.pc.in",
            "Makefile.am",
            "devtools/test_voikkospell_suggestions.sh.in",
            "devtools/generate-noun-wordforms.sh",
            "devtools/generate-verb-wordforms.sh",
            "devtools/generate-adj-wordforms.sh",
            "devtools/test_ospell-office_suggestions.sh.in",
            "devtools/generate-prop-wordforms.sh",
            "devtools/test_grammar_checker.sh.in",
            "devtools/check_analysis_regressions.sh.in",
            "m4/giella-macros.m4",
            "m4/ax_compare_version.m4",
            "m4/hfst.m4",
            "m4/ax_python_module.m4",
            "m4/ax_java_modules.m4",
            "m4/ax_check_gnu_make.m4",
            "m4/giella-config-files.m4",
            "docs/Makefile.am",
            "autogen.sh",
            "src/filters/Makefile.am",
            "src/filters/.gitignore",
            "src/cg3/Makefile.am",
            "src/orthography/Makefile.am",
            "src/hyphenation/Makefile.am",
            "src/Makefile.am",
            "src/transcriptions/Makefile.am",
            "src/phonetics/Makefile.am",
            "src/tagsets/Makefile.am",
            "src/fst/Makefile.am",
            "src/fst/.gitignore",
            "src/fst/Makefile.modifications-phon.am"]

optional = ["tools/mt/apertium/tagsets/README.txt",
            "tools/spellcheckers/index.xml",
            "tools/spellcheckers/index.mobile.xml",
            "tools/spellcheckers/weights/00README.txt",
            "tools/tokenisers/tokeniser-gramcheck-gt-desc.pmscript",
            "tools/tokenisers/tokeniser-disamb-gt-desc.pmscript",
            "tools/analysers/pipespec.xml.in",
            "tools/grammarcheckers/pipespec.xml.in",
            "tools/grammarcheckers/index.xml",
            "INSTALL",
            "AUTHORS",
            "README",
            "README.markdown",
            "LICENCE",
            "manifest.toml.in",
            "devtools/00README.txt",
            "src/fst/generated_files/00README.txt",
            "src/fst/incoming/00README.txt"]

ignored = [ "manifest.toml",
            "misc/00Readme.txt",
            "tools/mt/apertium/filters/00README.txt",
            "tools/mt/apertium/tagsets/apertium.postproc.relabel",
            "tools/mt/apertium/tagsets/gt2apertium.cg3relabel",
            "tools/mt/apertium/tagsets/README.txt",
            "tools/hyphenators/qya.tra",
            "tools/hyphenators/tags.reweight",
            "tools/spellcheckers/words.default.txt",
            "tools/spellcheckers/initial_letters.default.regex",
            "tools/spellcheckers/weights/spellercorpus.raw.txt",
            "tools/spellcheckers/weights/word-boundary.att",
            "tools/spellcheckers/weights/00README.txt",
            "tools/spellcheckers/weights/tags.reweight",
            "tools/spellcheckers/weights/word-boundary.relabel",
            "tools/spellcheckers/weights/word-boundary.txt",
            "tools/spellcheckers/strings.default.regex",
            "tools/spellcheckers/final_strings.default.regex",
            "tools/spellcheckers/errmodel.ocr.regex",
            "tools/spellcheckers/initial_letters.default.txt",
            "tools/spellcheckers/strings.default.txt",
            "tools/spellcheckers/editdist.default.txt",
            "tools/spellcheckers/final_strings.default.txt",
            "tools/tokenisers/mwe-dis.cg3",
            "tools/tokenisers/paradigm.abbr.txt",
            "tools/tokenisers/corpustags.txt",
            "tools/analysers/analyser-gt-whitespace.regex",
            "tools/grammarcheckers/spellchecker.cg3",
            "tools/grammarcheckers/errors.source.xml",
            "tools/grammarcheckers/grammarchecker.cg3",
            "tools/grammarcheckers/analyser-gt-whitespace.regex",
            "test/tools/mt/apertium/apertiumtests_mt-gt-desc.ana.yaml",
            "test/tools/spellcheckers/fstbased/fstspeller-gt-norm-yamls/spellertests_fstspeller-gt-norm.yaml",
            "test/tools/spellcheckers/fstbased/desktop/hfst/hfst-acceptor-yamls/words_acceptor.default.speller.yaml",
            "test/tools/spellcheckers/speller-gt-norm-yamls/basespellertests_speller-gt-norm.yaml",
            "test/data/analysis_check_corpus.txt",
            "test/data/typos.txt",
            "test/src/orthography/initcaptests_inituppercase.gen.yaml",
            "test/src/dict-gt-yamls/dicttests_dict-gt-desc.ana.yaml",
            "test/src/dict-gt-yamls/dicttests_dict-gt-norm.gen.yaml",
            "docs/tabs.xml",
            "docs/forrest.properties",
            "docs/index.xml",
            "docs/preamble.jspwiki",
            "docs/resources/images/group.png",
            "docs/resources/images/project.png",
            "docs/link-header.jspwiki",
            "docs/skinconf.xml",
            "docs/sitemap.xmap",
            "docs/site.xml",
            "src/filters/downcase_UCletters.regex",
            "src/cg3/dependency.cg3",
            "src/cg3/functions.cg3",
            "src/cg3/disambiguator.cg3",
            "src/orthography/inituppercase.regex",
            "src/orthography/spellrelax.regex",
            "src/orthography/downcase-derived_proper-strings.xfscript",
            "src/orthography/spellrelax-with-tags.xfscript",
            "src/orthography/spellrelax-tags.regex",
            "src/orthography/spellrelax-mobile-keyboard.regex",
            "src/orthography/allcaps.xfscript",
            "src/hyphenation/hyphenation.xfscript",
            "src/transcriptions/transcriptor-date-digit2text.lexc",
            "src/transcriptions/transcriptor-numbers-digit2text.lexc",
            "src/transcriptions/transcriptor-clock-digit2text.lexc",
            "src/phonetics/text2ipa-qya.xfscript",
            "src/fst/stems/nouns.lexc",
            "src/fst/stems/adjectives.lexc",
            "src/fst/stems/verbs.lexc",
            "src/fst/stems/pronouns.lexc",
            "src/fst/stems/prefixes.lexc",
            "src/fst/stems/numerals.lexc",
            "src/fst/root.lexc",
            "src/fst/affixes/symbols.lexc",
            "src/fst/affixes/nouns.lexc",
            "src/fst/affixes/adjectives.lexc",
            "src/fst/affixes/verbs.lexc",
            "src/fst/affixes/propernouns.lexc",
            "src/fst/phonology.twolc" ]
